In [3]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.7/dist-packages (0.1.70)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.8.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.27.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2021.10.8)

In [2]:
import yfinance as yf

In [8]:
twii = yf.Ticker("^TWII")

In [9]:
twii.info

{'algorithm': None,
 'ask': 0,
 'askSize': 0,
 'averageDailyVolume10Day': 3559620,
 'averageVolume': 4086572,
 'averageVolume10days': 3559620,
 'beta': None,
 'bid': 0,
 'bidSize': 0,
 'circulatingSupply': None,
 'currency': 'TWD',
 'dayHigh': 16345.84,
 'dayLow': 16090.54,
 'dividendRate': None,
 'dividendYield': None,
 'exDividendDate': None,
 'exchange': 'TAI',
 'exchangeTimezoneName': 'Asia/Taipei',
 'exchangeTimezoneShortName': 'CST',
 'expireDate': None,
 'fiftyDayAverage': 17246.729,
 'fiftyTwoWeekHigh': 18619.61,
 'fiftyTwoWeekLow': 15159.86,
 'fiveYearAvgDividendYield': None,
 'forwardPE': None,
 'fromCurrency': None,
 'gmtOffSetMilliseconds': '28800000',
 'isEsgPopulated': False,
 'lastMarket': None,
 'logo_url': '',
 'market': 'tw_market',
 'marketCap': None,
 'maxAge': 1,
 'maxSupply': None,
 'messageBoardId': 'finmb_INDEXTWII',
 'navPrice': None,
 'open': 16345.84,
 'openInterest': None,
 'payoutRatio': None,
 'preMarketPrice': None,
 'previousClose': 16408.2,
 'priceHint': 2,
 'priceToSalesTrailing12Months': None,
 'quoteType': 'INDEX',
 'regularMarketDayHigh': 16345.84,
 'regularMarketDayLow': 16090.54,
 'regularMarketOpen': 16345.84,
 'regularMarketPreviousClose': 16408.2,
 'regularMarketPrice': 16128.22,
 'regularMarketVolume': 0,
 'shortName': 'TSEC weighted index',
 'startDate': None,
 'strikePrice': None,
 'symbol': '^TWII',
 'toCurrency': None,
 'totalAssets': None,
 'tradeable': False,
 'trailingAnnualDividendRate': None,
 'trailingAnnualDividendYield': None,
 'twoHundredDayAverage': 17441.271,
 'volume': 0,
 'volume24Hr': None,
 'volumeAllCurrencies': None,
 'yield': None,
 'ytdReturn': None}

In [10]:
twii.financials

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [11]:
print(twii.history().columns)
twii.history()

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='object')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-04-11,17273.050781,17316.349609,17046.669922,17048.369141,4584600,0,0
2022-04-12,17005.839844,17100.849609,16905.130859,16990.910156,4100800,0,0
2022-04-13,17080.400391,17333.210938,17080.400391,17301.650391,4058700,0,0
2022-04-14,17353.250000,17374.140625,17245.650391,17245.650391,4429600,0,0
2022-04-15,17139.339844,17141.330078,17004.179688,17004.179688,4078400,0,0
2022-04-18,16958.660156,16999.359375,16845.509766,16898.869141,4020900,0,0
2022-04-19,16926.339844,17106.259766,16926.339844,16993.400391,3514900,0,0
2022-04-20,17057.130859,17148.880859,16983.550781,17148.880859,4801300,0,0
2022-04-21,17159.880859,17213.660156,17106.369141,17127.949219,3952000,0,0
2022-04-22,17088.759766,17088.759766,16923.869141,17025.089844,4322500,0,0
2022-04-25,16912.300781,16912.300781,16579.890625,16620.900391,4528800,0,0
2022-04-26,16677.839844,16729.470703,16582.109375,16644.789062,3941900,0,0
2022-04-27,16427.320312,16427.320312,16219.410156,16303.349609,4261400,0,0
2022-04-28,16350.719727,16455.570312,16256.879883,16419.380859,3635500,0,0
2022-04-29,16599.839844,16663.660156,16521.939453,16592.179688,3416300,0,0
2022-05-03,16593.210938,16604.869141,16465.990234,16498.900391,2457700,0,0
2022-05-04,16531.369141,16617.060547,16514.300781,16565.830078,2630000,0,0
2022-05-05,16689.980469,16783.779297,16650.810547,16696.119141,3215900,0,0
2022-05-06,16491.109375,16491.109375,16312.169922,16408.199219,3186200,0,0
2022-05-09,16345.839844,16345.839844,16090.540039,16125.919922,0,0,0

In [12]:
yf.download("^TWII",period="7d",interval="1m")

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2022-04-28 09:00:00+08:00,16350.719727,16400.150391,16350.719727,16384.759766,16384.759766,0
2022-04-28 09:01:00+08:00,16397.179688,16397.179688,16375.990234,16385.380859,16385.380859,0
2022-04-28 09:02:00+08:00,16382.389648,16382.389648,16352.410156,16352.410156,16352.410156,0
2022-04-28 09:03:00+08:00,16364.250000,16364.250000,16353.750000,16360.500000,16360.500000,0
2022-04-28 09:04:00+08:00,16363.019531,16363.940430,16346.179688,16357.440430,16357.440430,0
...,...,...,...,...,...,...
2022-05-09 11:17:00+08:00,16126.339844,16129.440430,16116.400391,16127.299805,16127.299805,0
2022-05-09 11:18:00+08:00,16126.589844,16128.959961,16119.919922,16128.860352,16128.860352,0
2022-05-09 11:19:00+08:00,16129.870117,16130.370117,16121.009766,16121.009766,16121.009766,0
2022-05-09 11:20:00+08:00,16126.049805,16128.440430,16118.129883,16119.379883,16119.379883,0
2022-05-09 11:21:35+08:00,16128.320312,16128.320312,16128.320312,16128.320312,16128.320312,0